[profile.default]
src = "src"
out = "out"
libs = ["lib"]
[rpc_endpoints]
mumbai = "${POLYGON_MUMBAI_NETWORK}"
binance = "${BINANCE_SMART_CHAIN}"
seploia="${SEPOLIA_NETWORK}"


[etherscan]
binance = { key = "DQ9ZQP351CG58WIJHYUMK4TQQXHHYTT1HJ", url = "https://bsc-dataseed.binance.org/" }


# See more config options https://github.com/foundry-rs/foundry/tree/master/config